{% set version = "1.11-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-arm
  version: {{ version|replace("-", "_") }}

source:
  fn: arm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/arm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/arm/arm_{{ version }}.tar.gz
  sha256: 8385be32f6b6b6f1b32df15f42073b191d714d870bbb4f95875b64aff6112bbf

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-matrix >=1.0
    - r-abind
    - r-coda
    - r-lme4 >=1.0
    - r-nlme
  run:
    - r-base
    - r-mass
    - r-matrix >=1.0
    - r-abind
    - r-coda
    - r-lme4 >=1.0
    - r-nlme

test:
  commands:
    - $R -e "library('arm')"           # [not win]
    - "\"%R%\" -e \"library('arm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=arm
  license: GPL (>= 3)
  summary: Functions to accompany A. Gelman and J. Hill, Data Analysis Using Regression and Multilevel/Hierarchical Models, Cambridge University Press, 2007.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ThimotheeV
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
