{% set version = "1.14-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-arm
  version: {{ version|replace("-", "_") }}

source:
  fn: arm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/arm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/arm/arm_{{ version }}.tar.gz
  sha256: 425bcb0afea2efb668d15ed8daa430bb356c62587eba806fd91e37afac1807bd

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-hmisc
    - r-mass
    - r-matrix >=1.0
    - r-abind
    - r-coda
    - r-lme4 >=1.0
    - r-nlme
  run:
    - r-base
    - r-hmisc
    - r-mass
    - r-matrix >=1.0
    - r-abind
    - r-coda
    - r-lme4 >=1.0
    - r-nlme

test:
  commands:
    - $R -e "library('arm')"           # [not win]
    - "\"%R%\" -e \"library('arm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=arm
  license: GPL-2.0-or-later
  summary: Functions to accompany A. Gelman and J. Hill, Data Analysis Using Regression and Multilevel/Hierarchical Models, Cambridge University Press, 2007.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - ThimotheeV
