{% set version = "1.15-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-arm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/arm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/arm/arm_{{ version }}.tar.gz
  sha256: 94478b0593d751f6c0b2336ed66fee216c7573442a776e5a1eb398a91a50466c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-matrix >=1.6_1.1
    - r-abind
    - r-coda
    - r-lme4 >=1.0
    - r-nlme
  run:
    - r-base
    - r-mass
    - r-matrix >=1.6_1.1
    - r-abind
    - r-coda
    - r-lme4 >=1.0
    - r-nlme

test:
  commands:
    - $R -e "library('arm')"           # [not win]
    - "\"%R%\" -e \"library('arm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=arm
  license: GPL-2.0-or-later
  summary: Functions to accompany A. Gelman and J. Hill, Data Analysis Using Regression and Multilevel/Hierarchical Models, Cambridge University Press, 2007.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - ThimotheeV
