travis:
  secure:
    BINSTAR_TOKEN: U7Fns1q3rUGscEHopiZwHv1J6ovTNPlrSv0O7F1olfSvrA61RcaaiqWZZ5AU0mcl57nTn3sPGopm1OMxRyv/ZVWzoEmipVPBbcr8CuNQqGchqqeVFHlESdeIaJaJU0gEJ6wS5O8tHNJB+0eImT5MqE7qiKhV9haa3kro+hhpRsRAbvNJmMxEdbAeLdqhe9VAmkL030rhZf6ItGUUYv8I4JT2ZYP/YwYN+b4tVY1Q3Ma8aZPIpNE7NYYtj1vJcNH/k3ycRxLg4RssKApSOXIiV2gryVZ8ngAlvRS5mx9GkjGnMAILT+xHJTrQNtYLmCOdYQkDbghvbWtIJNLIdrxvzzY8kujcoLm1rtr3vcfsasmnAbNlq5helRwO1i9OK9Fh11fyAykWztoL7P8rpVU4SYQDv9vATa9UsKDe71Yy/QQGDVhgTsLrNE2k5+yAVSptrPKv+T1Wk6keRPgkYXD+36bh30KzxeUBi5H+L/0YHskfEbRt48cSwv3E01ue/q7L7TU6vQDisqkJGxyPHA42EguDugMOubPdgtmlxMhYim1jIDmAIk60OEJihcE4diyeYQnvWtsS+3ccapFuPJoNqLpwNE0LtpiR++sNNv0KGDAnRCgZMnoKXWq7stRoUOzwk/9ltnXczomUnQl7ixCa4kYHL0tJLViUC9oC96hB1tc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
