travis:
  secure:
    BINSTAR_TOKEN: MMXCff9EPow8cIq+ekZdi1hTtQ5pAcd8nDpbtxcnYGrkvaDUPOUK5ir5JfUgfYY1fdOsXSelQCO+aLIxv5rH4axsAeAwxz37adU3Vm8CRUEkbrESPnKeiSA8s2PVLqH+oQ1v/PbAHxs+QYQyPZR9yAlgTx2kWxXg2KppVPdDQBgl3a9ZJlV+RE4V+CuYnaGaRfdQRaW+YE1EhYOXMoWw1K1tJO18ZFwXWGgIvO8A2x58QbO5VPpnu2UBXBjKmIedyldFppodTgqm8IB61q/z8KoCRn/vgXLU/bfvU/qNiPwNgH5n73A4Eo+b3FOtIjy8fEi8fovrW7yNNCYlOfCtJsz04/MTBxGphidIFFMsSHqWM/ZCxNLxCow/WFE17/H0fGr/8IgkF5x0II1WynUCQOgprji01dZo24QzYh3OybYnR0Q/fh9oUyvPOU1WR5tOMibemSIZcYHGtNBJMtCBV0JTexLwDJqlgDccSXS9A1NYtEPvIgUBgfIdkzSVt/UvT0Nn8KdGeoePqGP8rzqM8sHF1Z40YO7vFJl1twyGCI+D7bCWlq2hdP6WwwXY/OX5/smr+RFThUrGYrzwA+eo0hUCrOfXJvvqgf+NZUcG+QNJdWMM1wzs9ZYpgLWgtbuD9NRLQhnl8x4lnHSefikpbuYEleAkoFPmtUyQ9nbCQu0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
