appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: LCrWl0dUNS89Jv3xmF9Ku1OQMB5nwzOjadbTIn8NKbHP5jx2NBqEt7boORioklpiIa0tLK9wVxGsfcBoTqJ0RR5m23i9IxmRv4svsm0L/Pj2jyRZCiwPNoD/og02v0X5kojm9d69J76lxkWumNtxD2HURFdvS8daoAi4VzCo0M8D9DmwYlLLDDI4JsgR88AA7vn5j54BtoMaa/AoFlZC3/bRVEjKj5/BzE3nQSI0nWXQtqfSH81/Ogij8tWxpy+HDv8vSRA9qNf3DhDhnLgOv8RyYH2YGNwits+OHjGaYhC44sNuMTYAlOodJam8naZ45HE9KP4REX/bjYz7GSj3BUwNy6FP6oNOFWPblx7fPnAi//r539kgjyVbxUEbwQHptBCfJjL7Ffy60VPpY6e9S3JGWr8J4k2jaIww+NxGM18vdIbmS0dQ6KtipNNRbEmlGJ8yno4/yCZCufcxj2V0WiLAXOP5R9IFo7ZDTI0rEarsuPtZL8K30epStEAhkRoUxu6cc8XS1HBr+61YOgM+qMVWBMdb+9DDV2UXXCUnNr8Z29J6Xakw9v/6gZYrCUz//k2eNPiFYfaHlAo8iE9gwvpGTOvAJZYNBIbv29tI1er1dbyYTwxUkeXZut61uLYiezuHnxfYnCVS5+XoeUKgKPFCqQkf9EKETwbgsY9JIT0=}
bot:
  automerge: true
