travis:
  secure:
    BINSTAR_TOKEN: GbVFuyvN42SMl3D8orciBTSte9e+9ZMl0VnuXq3RsYbPRs+QZ8YM4VOWJk3IE93fQJmMLyD//YjkEH6KTsbFrMZC6GsKYhw/vbp9bc00B6Xb46uvBPnf6FmldYIIQd4jxsoEbVKKaLOx2FWMyk0JcrNVod+HGrNqATfSG+FP+LjhbQ+cWyRgBu7aSZZCkJYS5hQRVqQM7pRzVYc+AqqYJDmFnhvtSECbibNR2p/K7MwBkrDZm1rq5NABHUMSvoyVr6sV4bGNVLxe2WLIOFEguU9jOvkqI+GAAJH+3ELVXM9YD/tYhfS9rWCuwDywxMPbacjpPKVL+0pV79/bw7H4d3nmumuOEX3RjH9ltQbOvglydbYKR1sodmbGvfrAkHdYCtiYSRsZlM/IHGKGXiyfxNH2Y4Sts51YfrYzP5C6rs7CtG7Ph5sad5qyJqH2kBkThd4LAQFoNhHi6Bh7HM1ruqix/MuIddHYaqdqrQiJhgpZg5DiI2IzHfL+2MfW69HErHci1ZFPkQW+caZ5HEt2y1K9/GMWGvCpt255fHzXxR4rGT3d6hdQU2ZuUqAP033iGF2F0TwbvOg6MHagphkh6PehAlrooGcG6XrMgJOp9Y8H3JBaGhegU0kvxcAIgN1ZQZJreOejmhqgOOSFMfxDMXVzYHIMHKsC07nBnFHOtgY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
